### ISSUE TITLE
Incorrect japanese icon filename (jp.png, should be ja.png)

### ISSUE THREAD

**Issue by nvbooster** [sonata-project/SonataTranslationBundle#131]
## Subject
Wrong locale icon in locale switcher for japanese locale

File name: jp.png
Locale name: ja

## Steps to reproduce
sonata_translation:
    locales: [en, ja]
    default_locale: en
## Expected results
In top of admin GB and Japanese flags
## Actual results
Japanese flag icon has tag

`<img src="/bundles/sonatatranslation/img/flags/ja.png">`

which cannot be load  (as only jp.png presents in bundle resources)

**Comment by core23** [comment]
Can you provide a PR @nvbooster ?

**Comment by nvbooster** [comment]
Sure

sonata-project/SonataTranslationBundle#132

**Comment by dbu** [comment]
fixed in #132
