### ISSUE TITLE
flags: language codes vs country codes

### ISSUE THREAD

**Issue by dbu** [sonata-project/SonataTranslationBundle#133]
In #132 the icon for japanese language was added - we only had jp.png which is the country japan, not the language japanese.

A "locale" can be two letters, representing a language (en, fr, ja, ...). It can also be xx_XX, where the second part in capitals is the country. fr_CA, fr_CH, de_DE, de_CH, pt_BR and so on. In #132 we say that atm, this bundle would use the country code to locate a flag, which is wrong. fr_CA and en_CA is not the same at all, neither are de_CH and fr_CH.

I have seen people using diagonal mixes of the flag of the country that "owns" that language (UK for english, germany for german, france for french, portugal for portuguese, ...) and the other half the flag of the country specified in the locale. I can't find a good example, but a bit like this: http://www.shutterstock.com/pic-98969702/stock-vector-american-and-british-english-language-icon-useful-for-websites-isolated-vector-illustration.html

Technically, i think the sane solution is to allow to provide icons like fr_CA.png and write a twig helper that figures out what image file to include, falling back from fr_CA to fr.

**Comment by greg0ire** [comment]
> i hope there is way to overwrite icons? then people can choose whether they want a split french+canadian flag icon, or a quebec icon.

Maybe we should just let them choose what strategy to use ?

1. country strategy
2. map language to country, if no luck back to strategy #1
3. look for locale flag, if no luck use strategy #2

**Comment by dbu** [comment]
i think there is only one strategy: check for the specific icon xx_XX.png, and fall back to xx.png (not strtolower(XX).png). there is no language called brasilian, and no locale `br`, only `pt_BR`, so if you want an all brasilian flag, just provide it as pt_BR.png and you are good.

afaik a locale can not specify only the country, there is always the language part first.

**Comment by greg0ire** [comment]
> there is no language called brasilian, and no locale br, only pt_BR, so if you want an all brasilian flag, just provide it as pt_BR.png and you are good.

Yeah but there is language called portuguese, right ? So in this particular example, strategy 3 would be : 

1. Look for a flag for brasilian portuguese
2. If not found, try to map portugues to portugal, and if portugal is found by the mapping, display the flag of portugal
3. If not mapping is found (we didn't map pt to PT), display the flag of brasil (BR)

**Comment by dmarkowicz** [comment]
I think the solution should cover all locales from Symfony Intl Component `Intl::getLocaleBundle()->getLocaleNames()`. There are also other formats like az_Cyrl_AZ, az_Latn, az_Latn_AZ, zh_Hans_CN etc.

**Comment by greg0ire** [comment]
> I think the solution should cover all locales from Symfony Intl Component Intl::getLocaleBundle()->getLocaleNames(). There are also other formats like az_Cyrl_AZ, az_Latn, az_Latn_AZ, zh_Hans_CN etc.

The situation is getting more and more complicated :cold_sweat:

**Comment by dbu** [comment]
oh right, agree with @dmarkowicz. we should see if the intl component can offer help to parse those locales. 

i don't think falling back to only the country makes sense. for pt_BR, just provide pt_BR.png and it will work. for switzerland, showing a CH flag makes no sense, it must be one of de / fr / it. afaik locales can be shortened from the right and as soon as we find an icon file, we take that. left is the significant part, so falling back to only use the right part of it has no value.

**Comment by greg0ire** [comment]
> i don't think falling back to only the country makes sense

That's the easiest strategy, but I was not suggesting only doing that. I think we should go with at least strategy 2 which would display a french flag for fr_CH. and 3 / 4 would be nice to have.

**Comment by greg0ire** [comment]
Simple solution : [just don't use flags](https://web.archive.org/web/20160729234452/http://flagsarenotlanguages.com/blog/best-practice-for-presenting-languages/) from the late flagsarenotlanguages.com

**Comment by dbu** [comment]
yeah thats a matter of taste. it would be nice to have a strategy to
show language names rather than flags.

we don't have to provide everything. i think the important bit is that
what we do provide is not wrong, and ideally easy to extend / customize
with custom behaviour.

**Comment by greg0ire** [comment]
To do that, I think we need a Twig function that, given a locale, provides a piece of html, based on a strategy service the user should be able to configure. There could be a ChainStrategy to try different strategies one after the other in case of failure.

**Comment by gxgpet** [comment]
A similar issue for Hindi language flag: there is the `in.png` file, but the language spoken in India is Hindi, thus, the file should be named `hi.png`, because it represents the locale, not the country.

**Comment by scuben** [comment]
Run into this issue today with de_CH and fr_CH. I hope this issue will get some love. For me I solved it with overriding the template and using `locale|slice(0, 2)`.

**Comment by greg0ire** [comment]
Why not provide a PR @scuben ?

**Comment by scuben** [comment]
Would have if there would be more love to spend than using twig's slice function.

**Comment by greg0ire** [comment]
There is, see my answer.

**Comment by sonofliberty** [comment]
This is still an issue. I'm working with the Vietnamese locale (vi) which is different from the country code (vn).. so my language switcher shows the flag of the Virgin Islands or something instead of the Vietnamese one.

**Comment by greg0ire** [comment]
> This is still an issue.

Why don't YOU fix it?
