### ISSUE TITLE
Attempted to call an undefined method named "mergeNewTranslations"

### ISSUE THREAD

**Issue by BigBazooka007** [sonata-project/SonataTranslationBundle#154]
#### Sonata packages
sonata-project/admin-bundle              3.13.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.0  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/cache-bundle              2.3.1  This bundle provides caching services
sonata-project/classification-bundle     3.2.1  Symfony SonataClassificationBundle
sonata-project/core-bundle               3.2.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.3  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10 Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1  Lightweight Exporter library
sonata-project/formatter-bundle          3.1.0  Symfony SonataFormatterBundle
sonata-project/google-authenticator      1.0.2  Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle               2.3.0  Symfony SonataIntlBundle
sonata-project/media-bundle              3.3.1  Symfony SonataMediaBundle
sonata-project/notification-bundle       3.1.0  Symfony SonataNotificationBundle
sonata-project/page-bundle               3.3.0  This bundle provides a Site and Page management through container and block services
sonata-project/seo-bundle                2.1.0  Symfony SonataSeoBundle
sonata-project/timeline-bundle           3.1.0  Integrates SpyTimelineBundle into Sonata
sonata-project/translation-bundle        2.1.0  SonataTranslationBundle
sonata-project/user-bundle               3.2.1  Symfony SonataUserBundle

#### Symfony packages

symfony/monolog-bundle     v3.0.3  Symfony MonologBundle
symfony/phpunit-bridge     v3.2.3  Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.3.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.3.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.3.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.4.2  Symfony SwiftmailerBundle
symfony/symfony            v2.8.17 The Symfony PHP framework

#### PHP version

PHP 5.6.25 (cli) (built: Aug 18 2016 11:39:15)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

## Subject

I have installed this bundle according to documentation (using ORM models) and getting this error: Attempted to call an undefined method named "mergeNewTranslations" in my bundle. 

If i disable in my config of sonata_translation "knplabs" then it doesnt show any error but also not working properly - laungage switching makes no difference.

**Comment by greg0ire** [comment]
@BigBazooka007 can you provide a stack trace?

**Comment by OskarStark** [comment]
ping @BigBazooka007

**Comment by progmax** [comment]
same bug

**Comment by greg0ire** [comment]
This is not a stack trace.

**Comment by greg0ire** [comment]
From CONTRIBUTING.md : 

> If your issue is an error page, you must provide us with a stack trace. With recent versions of Symfony, you can even get stack traces as plain text at the end of the page. Just look for "Stack Trace (Plain Text)", and copy/paste what you see. Do not make a screenshot of the stack trace, as screenshots are not indexed by search engines and will make it difficult for other people to find your bug report. If you have an issue when using the Symfony CLI, use the -vvv option to get a stack trace.

**Comment by greg0ire** [comment]
@progmax that's better, but please give the full stack trace, not just the first line. If you think this is too long, you can wrap it in `<details>`, like this:


<details>
hello
</details>

**Comment by progmax** [comment]
This is all that displays....

**Comment by greg0ire** [comment]
That's strange, but ok… the `n/a` part is strange too.

**Comment by greg0ire** [comment]
[Here is what gives the error](https://github.com/sonata-project/SonataTranslationBundle/blob/master/Admin/Extension/Knplabs/TranslatableAdminExtension.php#L47). Shouldn't you have said method in your entity?

**Comment by progmax** [comment]
I do not see anything in the documentation:
https://sonata-project.org/bundles/translation/master/doc/reference/orm.html
Maybe I can not see well?

**Comment by greg0ire** [comment]
This class is intended for usage with 
knplabs/doctrine-behaviors . Are you using [this trait](https://github.com/KnpLabs/DoctrineBehaviors/blob/master/src/Model/Translatable/TranslatableMethods.php#L130), where the method is defined?

**Comment by progmax** [comment]
I do not use trait

**Comment by greg0ire** [comment]
The documentation code sample does though : https://sonata-project.org/bundles/translation/master/doc/reference/orm.html#implement-translatableinterface

**Comment by greg0ire** [comment]
The numbering in the doc is a bit weird, BTW:

```
3.6. B. Using KnpLabs Doctrine Behaviours
3.7. 1. Implement TranslatableInterface
```

**Comment by progmax** [comment]
Yes, everything is the same as in the documentation. (interface)

**Comment by greg0ire** [comment]
> I do not use trait

is in contradiction with

> Yes, everything is the same as in the documentation. (interface)

because the documentation shows : `use ORMBehaviors\Translatable\Translatable;`

So are you , or are you using this trait?

**Comment by progmax** [comment]
Now I have changed
```
class FAQCategory extends AbstractPersonalTranslatable implements TranslatableInterface
{
```

на

```
class FAQCategory implements TranslatableInterface
{
    use PersonalTranslatableTrait;

```

And got all the same error.

`[1] Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "mergeNewTranslations" of class "Application\сссBundle\Entity\Test".
Did you mean to call "getTranslations"?
    at n/a
        in /home/admin/web/ссс.biz/private/vendor/sonata-project/translation-bundle/Admin/Extension/Knplabs/TranslatableAdminExtension.php line 47
`

**Comment by greg0ire** [comment]
Why are you using this trait instead of `ORMBehaviors\Translatable\Translatable` ?

**Comment by OskarStark** [comment]
> of class "Application\сссBundle\Entity\Test"

the namespace looks strange, is it named `test? or ?FAQCategory`? Or do I mix some things up?

**Comment by progmax** [comment]
FAQCategory Copied from the documentation.
Is there a working example?

**Comment by greg0ire** [comment]
The documentation is split into two examples. FAQCategory is the first one, and is not meant to be used with `Admin/Extension/Knplabs/TranslatableAdminExtension.php`

**Comment by progmax** [comment]
The devil himself did not understand the documentation.

**Comment by dbu** [comment]
no need to call yourself a devil @progmax ;-) if you have suggestions how to clarify the doc, we are happy for pull requests to improve it.

**Comment by greg0ire** [comment]
@progmax we know it isn't ideal. I helped you figure it out, can you contribute something back to repay me? Like a small sentence to explain why there is a plan A and a plan B? Or a PR to fix the numbering, which does not look good? Or even something to split that page into 2 documents?

**Comment by progmax** [comment]
as much as I tried to settle the error is still the same.

**Comment by greg0ire** [comment]
> as much as I tried to settle

What does that mean? What did you try? Do you mean the KNP class is used although you did not ask for it in any way?

**Comment by progmax** [comment]
Both.

**Comment by greg0ire** [comment]
Purple.

**Comment by progmax** [comment]
Green :). And option A and option B. = error

**Comment by jordisala1991** [comment]
Can you make a gist of your entities at this point? maybe I can help you

**Comment by progmax** [comment]
unfortunately I already erased everything.

Did yet without bundle.

I had create field locale. And create records for each language. Of course that is not good.

**Comment by valerymelou** [comment]
Just ran into the same issue and I fixed it by explicitly installing and configuring `stof/doctrine-extensions-bundle`. Make sure you have the `translatable` extension enabled in `stof_doctrine_extensions` config.

**Comment by sujayjaju** [comment]
I fixed this issue by disabling KNP in the config:

``` yaml
sonata_translation:
    locales: [en, cn]
    default_locale: en
    # here enable the types you need
    gedmo:
        enabled: true
    knplabs:
        enabled: false
```
