### ISSUE TITLE
documentation title numerotation issue

### ISSUE THREAD

**Issue by lalop** [sonata-project/SonataTranslationBundle#159]
There is an issue on your markdown reader.
The title's hierarchy isn't respected https://sonata-project.org/bundles/translation/master/doc/reference/orm.html but it seems ok on the github preview https://github.com/sonata-project/SonataTranslationBundle/blob/2.x/Resources/doc/reference/orm.rst

**Comment by greg0ire** [comment]
It's not markdown, it's RST, and the tool we use is Sphinx, for the record.

**Comment by OskarStark** [comment]
This looks strange to me, it looks like using `Scenario` in a headline will cause some numeration

This...
![screenshot 2017-03-15 15 44 42](https://cloud.githubusercontent.com/assets/995707/23954023/81547af4-0996-11e7-9358-57135e7f93f2.png)
results in:
![Uploading Screenshot 2017-03-15 15.45.24.png…]()

And this...
![screenshot 2017-03-15 15 44 51](https://cloud.githubusercontent.com/assets/995707/23954059/95493554-0996-11e7-96ea-1509634950bf.png)
results in:
![screenshot 2017-03-15 15 45 17](https://cloud.githubusercontent.com/assets/995707/23954067/9b2b739c-0996-11e7-9e59-daed0ef0f2bf.png)

**Comment by greg0ire** [comment]
Can you try changing "Scenario" to "Whatever"?

**Comment by OskarStark** [comment]
> Can you try changing "Scenario" to "Whatever"?

will try

**Comment by OskarStark** [comment]
This works, I will provide a PR
![screenshot 2017-03-15 15 58 42](https://cloud.githubusercontent.com/assets/995707/23954708/4e738cae-0998-11e7-81f4-e5e9deb31cd6.png)
![screenshot 2017-03-15 15 58 46](https://cloud.githubusercontent.com/assets/995707/23954707/4e732354-0998-11e7-98d8-82941c243de9.png)

**Comment by greg0ire** [comment]
:astonished:

**Comment by OskarStark** [comment]
> 😲

yes, very strange...
