### ISSUE TITLE
'The Request object has not been set' with 'console sonata:admin:explain ...'

### ISSUE THREAD

**Issue by nathannau** [sonata-project/SonataTranslationBundle#164]
## Steps to reproduce

Excecute :

` console sonata:admin:explain ` _service_

## Actual results

>  [RuntimeException]
>  The Request object has not been set

## Solution 

In file "/Admin/Extension/AbstractTranslatableAdminExtension.php" line 71 replace 
```diff
- if ($admin->getRequest()) {
+ if ($admin->hasRequest()) {
    $this->translatableLocale = $admin->getRequest()->get(self::TRANSLATABLE_LOCALE_PARAMETER);
 }
```

**Comment by greg0ire** [comment]
It makes sense, since the console has no request. Can you please make a PR?

**Comment by OskarStark** [comment]
I highlighted the relevant part for better readability in your PR
