### ISSUE TITLE
Support for KnpLabs Doctrine Behaviours

### ISSUE THREAD

**Issue by almacbe** [sonata-project/SonataTranslationBundle#166]
I would like to know why you have remove support for knplabs doctrine behaviours in version 2.x. If you want I could try to add it again.

I know there are some open issue about it and I have to review them, and there is some test pending that I have to do it. I am sorry, I haven't enough time.

Thanks.

**Comment by greg0ire** [comment]
Can you have the commit / PR where it was removed?

**Comment by almacbe** [comment]
I apologise to you. My mistake, I was confuse and I thought it was removed. Thanks
