### ISSUE TITLE
How to use this to translate models from other sonata bundles like NewsBundle

### ISSUE THREAD

**Issue by valerymelou** [sonata-project/SonataTranslationBundle#175]
I've managed to get this bundle to work for my custom entities. Now I wanted to know if it's possible to use it to translate models from `SonataNewsBundle` and if so, how do I do it? Thanks.

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
