### ISSUE TITLE
SonataTranslationBundle + SonataAdminBundle

### ISSUE THREAD

**Issue by jordscream** [sonata-project/SonataTranslationBundle#21]
Hello Nicolas,

great thing to develop SonataTranslationBundle
I setup everything and I success to have flag in the form edition in my Back Office (for ArticleAdmin Edition for example)

Anyway, I can click on flag, the page refresh with tl=en in get variable. But when I save my form, nothing is saved concernintgthe translations.

Do I miss something ? Do I modify the code of my ArticleAdmin?

Thanks
Jordan

**Comment by nicolas-bastien** [comment]
@jordscream does @jasperdcbe comment helped you ?
Do you still have the problem ?

**Comment by ThibautAlgrin** [comment]
Hey everyone,

I had this error with 1.0.0 version. But this bug was solved in dev-master.

**Comment by nicolas-bastien** [comment]
So I guess we can consider this as closed ?

**Comment by ThibautAlgrin** [comment]
Yes you can.

Can you also create a new version, or you want to add other functionality?

**Comment by rmed19** [comment]
Hey everyone,

I had this error  with "sonata-project/translation-bundle":"1.0.1", @jasperdcbe comment  helped me to fix it.
I think it will be necessary to add this to official documentation.

**Comment by nicolas-bastien** [comment]
ok @rmed19 I'll close this adn we'll finish in Your PR.

thanks
