### ISSUE TITLE
Bigger flag icons

### ISSUE THREAD

**Issue by lukepass** [sonata-project/SonataTranslationBundle#222]
This is more a feature request, is it possible to get bigger flag icons for translatable items?
They are rather small and difficult to recognize, especially for **visually impaired** people.

![image](https://user-images.githubusercontent.com/6429961/35683040-fb760dc8-0762-11e8-9a1d-4b57093353e9.png)

Thanks.

**Comment by OskarStark** [comment]
Sounds good to me, could you provide a PR?

**Comment by lukepass** [comment]
Maybe we could use this project giving credit to the author?

https://github.com/lipis/flag-icon-css

**Comment by lukepass** [comment]
There is also this project using a MIT license: https://www.gosquared.com/resources/flag-icons/

**Comment by dmarkowicz** [comment]
I agree it is time to improve flags. Please consider #133. The libraries you have indicated provide country flags, not language flags. So you need also to map country code to language code (in a way that satisfies everyone). For example:
pt_BR Portugal or Brazil? lets say 2nd part BR
but
fr_CA France or Canada? here 2nd part CA does not fit
This is currently done by dupliacting files and should also be improved.
