### ISSUE TITLE
CSS class sonata-bc.locale_{locale} value not set

### ISSUE THREAD

**Issue by jasperdcbe** [sonata-project/SonataTranslationBundle#25]
Apparently the sonata-bc.locale_{locale} class is not added on the body tag automatically. When adding the class manually to the body tag using Firebug the locale flags appear in the input fields.

How should the class be added to the body tag? I went through the source code but couldn't find something like a twig helper or event. 

Is it possible to add the class using the events?

**Comment by nicolas-bastien** [comment]
Hi @jasperdcbe, you should override the block body_attributes of sonata layout to add : 

    {% if (object.locale is defined) %}locale_{{ object.locale }}{% endif %}

so the code should looks like this : 

    {% block body_attributes %}
    class="sonata-bc {% if _side_menu is empty %}sonata-ba-no-side-menu{% endif %}{% if not app.user %} login-screen{% endif %} {% if (object.locale is defined) %}locale_{{ object.locale }}{% endif %}"
    {% endblock %}

Does this solves your problem ?

**Comment by jasperdcbe** [comment]
@nicolas-bastien  thanks for your reply. I'm not sure if it will solve the problem, and right now I won't be able to test it anymore in the project I was working on. But it looks like a good solution, thanks!

**Comment by nicolas-bastien** [comment]
@jasperdcbe I'll check if it's not clear in the doc but this is the way I implement it on my project.
