### ISSUE TITLE
http://sonata-project.org/bundles/translation/master/doc/reference/orm.html

### ISSUE THREAD

**Issue by malutanpetronel** [sonata-project/SonataTranslationBundle#29]
Can you please specify how to Implement TranslatableInterface if I am not using annotations for ORM but I use YML as bellow:

Cat.orm.yml
##########
Blogger\BlogBundle\Entity\Cat:
    type: entity
    table: cat
    repositoryClass: Blogger\BlogBundle\Entity\Repository\CatRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 45
    manyToMany:
        blogs:
            targetEntity: Blog
            mappedBy: cats

and the 2 classes (I use base classes)

BaseCat.php
########
<?php

namespace Blogger\BlogBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Cat
 */
class BaseCat
{
    /**
     * @var integer
     */
    public $id;

    /**
     * @var string
     */
    public $name;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    public $blogs;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->blogs = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }
....

Cat.php
#####

<?php
namespace Blogger\BlogBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Blogger\BlogBundle\Entity\BaseCat;

/**
 * Blogger\BlogBundle\Entity\Cat
 *
 * @ORM\Entity(repositoryClass="Blogger\BlogBundle\Entity\Repository\CatRepository")
 */
class Cat extends BaseCat
{
    public function __toString()
    {
      return $this->getName();
    }
}

I will mention that the flow I am using allows me to have always in git a Workbench schema in update with the models, which have a base class for keeping some method needed, and I am mentioning sonata admin nicely creates blog_has_cat records... Everything goes well.

What I cannot find is the implementation for this ORM side in contrast with annotations

**Comment by nicolas-bastien** [comment]
Hi @malutanpetronel, 

Example of yaml and xml mapping can be found in the gedmo documentation.
https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/translatable.md#yaml-mapping

I guess for a quick fix you can define yml mapping for the base translation classes : 
- AbstractTranslatable 
- AbstractPersonalTranslation

or to use trait and directly do the mapping in your entity.

Does this solves your problem ?

If you want to contribute to the doc, your welcome

**Comment by nicolas-bastien** [comment]
Hi @malutanpetronel I guess you found a way to make this work.

I close this but feel free to ping me if it's not solved for you
