### ISSUE TITLE
composer problem

### ISSUE THREAD

**Issue by legalcash** [sonata-project/SonataTranslationBundle#302]
[Composer\DependencyResolver\SolverProblemsException]                                                                                
  Problem 1                                                                                                                            
      - Installation request for sonata-project/translation-bundle ^2.3 -> satisfiable by sonata-project/translation-bundle[2.x-dev].  
      - remove stof/doctrine-extensions-bundle 1.3.x-dev|keep stof/doctrine-extensions-bundle dev-master                               
      - stof/doctrine-extensions-bundle dev-master conflicts with sonata-project/translation-bundle[2.x-dev].                          
      - Installation request for stof/doctrine-extensions-bundle ^1.3 -> satisfiable by stof/doctrine-extensions-bundle[1.3.x-dev].

You have restrict version drom 1.1 to 2
but stof/doctrine-extensions-bundle  is 1.3

**Comment by core23** [comment]
Can you provide a PR? @legalcash
