### ISSUE TITLE
Allow dynamic values for sonata_translation.locales config node

### ISSUE THREAD

**Issue by BrianWalters** [sonata-project/SonataTranslationBundle#303]
## Feature Request

Normally, if I wanted to use SonataTranslationBundle to allow French, English, and German, I would set this option:

```
sonata_translation:
    locales: ['de_DE','en_GB','fr_FR']
```

However, Symfony allows creating array variables by using environment processors. So if I would imagine if I made an environment variable like so:

```
# .env

LOCALES='["de_DE","en_GB","fr_FR"]'
```

And set the configuration like this:

```
sonata_translation:
    locales: '%env(json:LOCALES)%'
```

Everything would work. Alas:

> A dynamic value is not compatible with a "Symfony\Component\Config\Definition\PrototypedArrayNode" node type at path "sonata_translation.locales".

It would be nice to be able to set locales based on environment. I am looking for a workaround in the meantime.

**Comment by bhaktaraz** [comment]
> locales: '%env(json:LOCALES)%'

Did you get a solution for this @BrianWalters. I'm looking for the same, Can't find it in the docs.

**Comment by eerison** [comment]
I guess this issue wasn't solved 👀

**Comment by franmomu** [comment]
There are some issues about this in Symfony itself: https://github.com/symfony/symfony/issues/40906, https://github.com/symfony/symfony/pull/29270, https://github.com/symfony/symfony/issues/28599

So I would wait for a solution there.
