### ISSUE TITLE
FatalErrorException in LocaleSwitcherBlockService.php line 63:

### ISSUE THREAD

**Issue by piergi74** [sonata-project/SonataTranslationBundle#31]
I get this error after recent updates:

FatalErrorException in LocaleSwitcherBlockService.php line 63:
Compile Error: Declaration of Sonata\TranslationBundle\Block\LocaleSwitcherBlockService::validateBlock() must be compatible with Sonata\BlockBundle\Block\BlockAdminServiceInterface::validateBlock(Sonata\CoreBundle\Validator\ErrorElement $errorElement, Sonata\BlockBundle\Model\BlockInterface $block)

In composer.json I have:

        "sonata-project/admin-bundle": "~2.4@dev",
        "sonata-project/doctrine-orm-admin-bundle": "~2.4@dev",
        "sonata-project/translation-bundle": "2.3.*"

**Comment by rande** [comment]
Please review: https://gist.github.com/rande/9c0cfbd751d3e64b893f

**Comment by piergi74** [comment]
I checked that out already.
The problem is still there

**Comment by rande** [comment]
A PR is available to fix the issue: https://github.com/sonata-project/SonataTranslationBundle/pull/30 @nicolas-bastien can you review the PR ?
