### ISSUE TITLE
TranslationBundle not compatible with SonataAdmin 2.4

### ISSUE THREAD

**Issue by pauliek** [sonata-project/SonataTranslationBundle#40]
Hello,

the bundle is no longer compatible with latest SonataAdminBundle (i have 2.4@dev), because the ErrorElement class moved from the namespace Sonata\AdminBundle\Validator\ErrorElement to Sonata\CoreBundle\Validator\ErrorElement, so the declaration of the validateBlock method from LocaleSwitcherBlockService is no longer compatible with that of BlockAdminServiceInterface.

The solution seems to be to update the namespace usage in LocaleSwitcherBlockService from:

use Sonata\AdminBundle\Validator\ErrorElement;

to

use Sonata\CoreBundle\Validator\ErrorElement;

Thanks,
Paul

**Comment by ppetermann** [comment]
in the master branch the two empty methods have been removed which is a better solution than adding the use, however, apparently no one has create a release with that yet (1.0.1, someone?), so the composer require for 1.0 defaults to 1.0.0, which is the broken version.

**Comment by rande** [comment]
@nicolas-bastien can you create a tag ?

**Comment by nicolas-bastien** [comment]
@pauliek as @ppetermann said master is ok.

I'll make a tag this week, just want to do a clean changelog by the way

**Comment by pauliek** [comment]
Thanks, glad it's fixed now.

**Comment by Soullivaneuh** [comment]
ping @nicolas-bastien 

Please do it after #43.

Thanks.
