### ISSUE TITLE
Sonata - 4.0.0-alpha-1 missing requirement

### ISSUE THREAD

**Issue by v10mthibault** [sonata-project/SonataTranslationBundle#478]
#### Sonata packages

<details><summary>
       "sonata-project/admin-bundle": "4.0.0-alpha-1",
        "sonata-project/doctrine-orm-admin-bundle": "4.0.0-alpha-1",
        "sonata-project/translation-bundle": "4.0.0-alpha-1",
</summary>
<p>
sonata-project/translation-bundle doesn't work with alpha.
</p>
</details>

**Comment by greg0ire** [comment]
Closing because… scratch that, I feel too lazy to explain why after having to read this.

**Comment by VincentLanglet** [comment]
See https://github.com/sonata-project/SonataTranslationBundle/pull/477
