### ISSUE TITLE
Choose how to translate numbers / dates?

### ISSUE THREAD

**Issue by bhyassine** [sonata-project/SonataTranslationBundle#483]
## Feature Request

Hello,

I am using Sonata Translation Bundle and that's works extremely well. However, when I used it to translate into some particular languages (arabic for example), it translates the number from the arabic numbers "0,1,2,..." to the indian numbers "٠/١/٢/٣" used in some arabic states...

Is it possible to choose if we want to "translate" numbers or use always the same numbers.

Thank you!

**Comment by franmomu** [comment]
Hi @bhyassine,

The bundle allows you to translate your models providing integrations with [`gedmo`](https://github.com/doctrine-extensions/DoctrineExtensions) and [`knplabs`](https://github.com/KnpLabs/DoctrineBehaviors) but as far as I know it does not translate anything, can you please provide some context?
