### ISSUE TITLE
Not compatible with StofDoctrineExtensionsBundle >= 1.1.0

### ISSUE THREAD

**Issue by paq85** [sonata-project/SonataTranslationBundle#58]
https://github.com/stof/StofDoctrineExtensionsBundle/issues/299

It seems like the easiest way to fix it is to make the required service public again.

**Comment by jorrit** [comment]
Isn't it a better idea to just inject the translatable listener via `<argument type="service" id="stof_doctrine_extensions.listener.translatable" />` in `service_gedmo.xml`? Or is that not going to work for some reason?

**Comment by nicolas-bastien** [comment]
Hi @paq85 I show your question on stof bundle.

@jorrit is right working with alias will solve your problem.

We shoul create an alias : 'gedmo.listener.translatable' pointing to stof_doctrine_extensions.listener.translatable and update my gedmo extension code.

Do you want to try a PR ?

**Comment by jorrit** [comment]
@nicolas-bastien  are you asking me? Or @paq85 ? I am not yet familiar with aliases.

**Comment by nicolas-bastien** [comment]
@jorrit feel free to do it if you want, just post a comment to let every body know.

If you can't I can do that (I hope this week)

**Comment by nicolas-bastien** [comment]
@paq85 can you confirm it's ok for you now ?

**Comment by braianj** [comment]
I got this error

> Unable to replace alias "sonata_translation.listener.translatable" with actual definition "stof_doctrine_extensions.listener.translatable".

Are we talking about the same?
