### ISSUE TITLE
TranslationBundle overrides settings from stofBundle

### ISSUE THREAD

**Issue by liquorvicar** [sonata-project/SonataTranslationBundle#61]
In \Sonata\TranslationBundle\Admin\Extension\Gedmo\TranslatableAdminExtension, we are retrieving the TranslatableListener from the stofBundle and changing some settings on it. This caused us an issue on our project as we wanted to be able to set the TranslatableLocale and the Fallback boolean separately from the values that are hardcoded here. We achieved this by overridding the "sonata_translation.admin.extension.gedmo_translatable.class" parameter with the name of our own class.

I'm wondering if perhaps this should be tidied up. Maybe we could either just let the stof Listener do its thing and allow it be configured separately or possibly introduce our own config settings in this bundle which themselves could inherit the stof settings. I think the former would be my preference (as that's how we dealt with the issue in our project).

What do people think? I'm happy to start a PR if you think this would a valuable change. This would also resolve the issue in https://github.com/sonata-project/SonataTranslationBundle/issues/58 as we wouldn't need to load the private service from stof.

**Comment by dbu** [comment]
i am not promising to take over maintainance of this bundle, but i am currently looking over the open issues and try to do a bit of cleanup.

the code in the gedmo admin extension seems to fix gedmo to the requested locale (which might be different from the request locale, e.g. an english person looking at a french article does not want the navigation to switch to french as well...). i am not sure we can get rid of this. 

if the admin extension has some post save callback, we might be able to safe the things from the translatable listener and restore them after saving... or am i misunderstanding things? another way out could be to make language pinning optional - but i am not sure of the side effects.

**Comment by OskarStark** [comment]
@dbu this issue is very old and still no feedback from @liquorvicar, we should close this issue
