### ISSUE TITLE
Checks in AdminExtensionCompilerPass not in sync with TranslatableChecker

### ISSUE THREAD

**Issue by jorrit** [sonata-project/SonataTranslationBundle#62]
The class `AdminExtensionCompilerPass` checks for translatability by using the configured `instanceof` and `implements` settings. However, there is also a `TranslatableChecker` that performs these checks in addition to checking for the trait `Sonata\TranslationBundle\Traits\Translatable`. I think it is nicer when `AdminExtensionCompilerPass` uses the service `TranslatableChecker` to check for translatability, if that is possible.

**Comment by nicolas-bastien** [comment]
@jorrit I agree, so maybe you can do a PR to add this ?

**Comment by jorrit** [comment]
I'll try this or the next week!

**Comment by nicolas-bastien** [comment]
ok great ! waiting for your PR

**Comment by dbu** [comment]
@jorrit did you ever do that pull request? i intend to do a cleanup release soon, would be nice to fix this one.
