### ISSUE TITLE
Importing styles: not clear what to do

### ISSUE THREAD

**Issue by Uplink03** [sonata-project/SonataTranslationBundle#65]
The Installation section says this:

> Extend SonataAdmin layout if it's not already done

What exactly is one supposed to do? Where is that layout file? Is it `vendor/sonata-project/admin-bundle/Resources/views/standard_layout.html.twig` perchance?

**Comment by nicolas-bastien** [comment]
@Uplink03 To add this bundle you need to add custom css so you need to extends sonata standard layout.

Sonata configuration allow you to point to a custom template as a layout .

Here is an example : 

    sonata_admin:
    
        templates:
            layout: admin/layout.html.twig

and in this template : 

    {% extends "SonataAdminBundle::standard_layout.html.twig" %}

    {% block stylesheets %}
        {{  parent() }}
        {% stylesheets
        '@SonataTranslationBundle/Resources/public/css/sonata-translation.css'
        %}

        <link rel="stylesheet" href="{{ asset_url }}" />
        {% endstylesheets %}
    {% endblock %}

**Comment by nicolas-bastien** [comment]
Is it ok for you @Uplink03  ?

I think I can update the doc to add this.

**Comment by OskarStark** [comment]
i highlighted your code examples ;)

**Comment by Uplink03** [comment]
Yeah, that's what I needed to know. Thanks. It should be explained like this in the doc.

**Comment by OskarStark** [comment]
@Uplink03 can you provide a PR for the docs?
