### ISSUE TITLE
Undefined index: default_locale during installation

### ISSUE THREAD

**Issue by thitami** [sonata-project/SonataTranslationBundle#76]
Hi,

First of all, I would like to thank you for all your work with SonataTranslationBundle. 

I have created a fork of this bundle in order to contribute to an existing issue, using Symfony2.
However, when I am starting the Symfony built-in server or try to clear the cache with `php app/console cache:clear --no-warmup -v`, I am receiving the following exception:

`[Symfony\Component\Debug\Exception\ContextErrorException]  
  Notice: Undefined index: default_locale`

which comes from `sonata-project/translation-bundle/DependencyInjection/SonataTranslationExtension.php:35`.

To give some details about my local configuration: I declare `default_locale` in my config.yml file under framework: 
```
framework:
 //some declarations here
default_locale: %default_locale%
//some other declarations here
```

The value of `default_locale` in parameters.yml is "en".

Has anyone experienced this? If it is the latter, any suggestions would be highly appreciated.  I am trying to figure out whether this is an issue of the bundle or of my local configuration. 

Stack: MacOS El Capitan/ PHP 5.5.27 / Symfony 2.8.2

**Comment by dbu** [comment]
it seems the bundle is expecting its own configuration like this:

```
        sonata_translation:
            locales: [en, fr]
            default_locale: en
```

you can use `%default_locale%` in the bundle configuration too, as usual. but you need to explicitly specify the default locale to the translation bundle, its not pulled from the global value. i will make a pull request to fix the Configuration class so this is properly reported.
