### ISSUE TITLE
Non-existent service "stof_doctrine_extensions.listener.translatable"

### ISSUE THREAD

**Issue by jdumaz** [sonata-project/SonataTranslationBundle#79]
I have an error : **You have requested a non-existent service "stof_doctrine_extensions.listener.translatable".**

I currently use the last dev-master (7cad043) of sonata-project/translation-bundle and I had the same error with version 1.0.1.

Here is my composer.json file:

[composer.zip](https://github.com/sonata-project/SonataTranslationBundle/files/173641/composer.zip)

Note: In version 1.0.1 the error was only present on editing the object, since the dev-master the problem is global and I get a second error related to the first error : **Unable to replace alias" sonata_translation .listener.translatable "with actual definition" stof_doctrine_extensions.listener.translatable ".**

**Comment by greg0ire** [comment]
Can you use hastebin or gist or directly paster your composer.json here?

**Comment by jdumaz** [comment]
composer.json : [http://hastebin.com/havikacagu.dos](url)
packages installed : [http://hastebin.com/ezuqijadas.hs](url)

**Comment by greg0ire** [comment]
Looks like the doctrine extensions bundle was not installed.

**Comment by greg0ire** [comment]
Could you make a PR to change this line : 

https://github.com/sonata-project/SonataTranslationBundle/blob/master/composer.json#L33

From : 

> "stof/doctrine-extensions-bundle": "~1.1",

to 

> "stof/doctrine-extensions-bundle": "~1.1 if you want to use <whatever it is that needs the extensions bundle>",

**Comment by greg0ire** [comment]
ping @jdumaz

**Comment by jdumaz** [comment]
Sorry, I'm new on Github, PR is a Pull Request? How to do ?

**Comment by greg0ire** [comment]
> PR is a Pull Request?

Yes. I see this would be your first contribution, that's great because it is an easy one.

1. Go on this page https://github.com/sonata-project/SonataTranslationBundle/blob/master/composer.json ;
2. Click the little pencil to edit the file;
3. The rest should go very smoothly.

**Comment by jdumaz** [comment]
I added `"suggest": {
        "stof/doctrine-extensions-bundle": "~1.1"
    },` in my composer.json file, and I also tried `composer require stof/doctrine-extensions-bundle` but without success

**Comment by greg0ire** [comment]
> I added "suggest": { "stof/doctrine-extensions-bundle": "~1.1" }, in my composer.json file

This won't do anything.

> and I also tried composer require stof/doctrine-extensions-bundle

This should have. What did it output?

**Comment by jdumaz** [comment]
Same error as above.

**Comment by greg0ire** [comment]
What did this very command `composer require stof/doctrine-extensions-bundle` output?

**Comment by greg0ire** [comment]
Plus, it is a bundle, so you have to register it and configure it and read its documentation.

**Comment by jdumaz** [comment]
[Output](http://hastebin.com/ijocahupuh.tex)

**Comment by greg0ire** [comment]
> Plus, it is a bundle, so you have to register it and configure it and read its documentation.

**Comment by jdumaz** [comment]
I forgot to configure StofDoctrineExtensionsBundle. : s
Thank you, it works.
Sorry for the inconvenience.

**Comment by greg0ire** [comment]
Ok so now, the tiny PR. Can you try what I advised?

**Comment by jdumaz** [comment]
Ok it's done. ;)

**Comment by greg0ire** [comment]
Doesn't look like it… did you really go all the way? There should have been a form so that you can propose your change.

**Comment by jdumaz** [comment]
Sorry I was not validated. :D

**Comment by greg0ire** [comment]
Ok now it is good.
