### ISSUE TITLE
Make translation bundle compatible with other sonata admin bundle ~3.0.0

### ISSUE THREAD

**Issue by christian-kolb** [sonata-project/SonataTranslationBundle#98]
The sonata admin bundle and a lot of the others are available in version `~3.0.0`. Even the master version of the translation bundle still requires `^2.3.0|~2.4@dev`. When using the translation bundle it's not possible to update to the latest stable version.

**Comment by greg0ire** [comment]
See https://github.com/sonata-project/SonataAdminBundle/issues/3731
